language: cpp

sudo: true

matrix:
   include:
    - compiler: clang
      env: LLVM_VER="-3.4"
    - compiler: clang
      env: LLVM_VER="-3.5"
    - compiler: clang
      env: LLVM_VER="-3.6"
    - compiler: gcc
      env: COVERAGE=true

before_install:
 - if [[ $CXX == "g++" ]]; then sudo pip install cpp-coveralls; export CXX="g++-4.8"; export CXX_PKG="g++-4.8"; fi
 - sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/trusty.list
 - sudo sed -i "s/precise/trusty/g" /etc/apt/sources.list.d/trusty.list
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y flexc++ bisonc++ llvm$LLVM_VER-dev $CXX_PKG libboost-program-options-dev python3

script: make tests

after_success:
 - if [[ $COVERAGE ]]; then coveralls --gcov-options '\-lp' -t $COV_TOKEN -e scanner.cpp -e scanner.h -e scannerbase.h -e parser.cpp -e parser.h -e parser.ih -e parserbase.h; fi
