language: cpp

matrix:
   include:
    - compiler: clang
    - compiler: gcc
      env: COVERAGE=true

before_install:
 - sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/trusty.list
 - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list.d/trusty.list
 - export CXX_PKG=$(if [[ $CXX == "g++" ]]; then echo "g++"; fi)
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y flexc++ bisonc++ llvm-dev $CXX_PKG python3 libboost-program-options-dev
 - if [[ $CXX == "g++" ]]; then sudo pip install cpp-coveralls; fi

script: make tests

after_success:
 - coveralls --gcov-options '\-lp' -t $COV_TOKEN -e scanner.cpp -e scanner.h -e scannerbase.h -e parser.cpp -e parser.h -e parser.ih -e parserbase.h
