language: cpp
dist: trusty
sudo: required

matrix:
   include:
    - compiler: clang
      env: LLVM_VER="-3.4"
    - compiler: clang
      env: LLVM_VER="-3.5"
    - compiler: clang
      env: LLVM_VER="-3.6"
    - compiler: clang
      env: LLVM_VER="-3.8"
    - compiler: clang
      env: LLVM_VER="-3.9"
    - compiler: clang
      env: LLVM_VER="-4.0"
    - compiler: gcc
      env: COVERAGE=true

before_install:
 - ./travisSetup.sh

script: cd src && make frontend && make -j2 tests

after_success:
 - if [[ $COVERAGE ]]; then coveralls --gcov-options '\-lp' -t $COV_TOKEN -e scanner.cpp -e scanner.h -e scannerbase.h -e parser.cpp -e parser.h -e parser.ih -e parserbase.h; fi
