language: cpp

sudo: false

matrix:
   include:
    - compiler: clang
      env: LLVM_VER="-3.4"
    - compiler: clang
      env: LLVM_VER="-3.5"
    - compiler: clang
      env: LLVM_VER="-3.6"
    - compiler: clang
      env: LLVM_VER="-3.7"
    - compiler: gcc
      env: COVERAGE=true

addons:
   apt:
      sources:
       - llvm-toolchain-precise-3.5
       - llvm-toolchain-precise-3.6
       - llvm-toolchain-precise-3.7
       - ubuntu-toolchain-r-test
       - debian-sid
      packages:
       - flexc++
       - bisonc++
       - g++-4.8
       - llvm-3.4-dev
       - llvm-3.5-dev
       - llvm-3.6-dev
       - llvm-3.7-dev
       - python3
       - libboost-program-options-dev

before_install:
 - if [[ $CXX == "g++" ]]; then export CXX="g++-4.8"; fi
 - if [[ $CXX == "g++" ]]; then pip install cpp-coveralls; fi

script: make tests

after_success:
 - if [[ $COVERAGE ]]; then coveralls --gcov-options '\-lp' -t $COV_TOKEN -e scanner.cpp -e scanner.h -e scannerbase.h -e parser.cpp -e parser.h -e parser.ih -e parserbase.h; fi
